'use strict';

const Actions = {
    LOADPORTAL : "LOADPORTAL",
    PORTALLOADED: "PORTALLOADED",
    UPDATEPORTAL : "UPDATEPORTAL",
    REARRANGEPORTAL : "REARRANGEPORTAL",
    STATICPORTAL : "STATICPORTAL",
    SAVEPORTAL : "SAVEPORTAL",
    PINTODASHBOARD : "PINTODASHBOARD",
    ADDEDAPPTOPORTAL : "ADDEDAPPTOPORTAL",
    REMOVECARD : "REMOVECARD"
}

export default Actions;